tasks:
  - init: pnpm install
vscode:
  extensions: [
    "ms-azuretools.vscode-docker",
    "ms-vscode-remote.remote-containers",
    "dbaeumer.vscode-eslint",
    "Gruntfuggly.global-config",
    "ms-vsliveshare.vsliveshare",
    "pnp.polacode",
    "esbenp.prettier-vscode",
    "solidjs-community.solid-snippets",
    "bradlc.vscode-tailwindcss",
    "wayou.vscode-todo-highlight",
    "EditorConfig.EditorConfig",
    "mikestead.dotenv"
  ]
